let JobsData = [
  {
    "jobId": "98f7d9ds8fdsgf",
    "companyLogo": "https://logo.clearbit.com/google.com",
    "companyName": "Google",
    "state": "Karnataka",
    "jobDescription": "We are looking for a talented frontend developer with React.js expertise. You will work on building high-performance, scalable web applications for global users. Must be able to write clean and maintainable code.",
    "employmentStatus": "Full-time",
    "vacancies": { "count": 3, "icon": "fa-users" },
    "position": { "title": "Frontend Developer", "icon": "fa-code" },
    "weeklyHours": { "hours": 40, "icon": "fa-clock" },
    "salary": { "amount": "12 LPA", "icon": "fa-money-bill" },
    "workplace": "WFO",
    "qualification": "B.Tech in Computer Science or related field",
    "experience": "2-4 years"
  },
  {
    "jobId": "a72k3hj9sfd93",
    "companyLogo": "https://logo.clearbit.com/microsoft.com",
    "companyName": "Microsoft",
    "state": "Telangana",
    "jobDescription": "Join our team as a software engineer where you will design and implement cloud solutions. You'll work with Azure and contribute to microservices architecture in a collaborative environment.",
    "employmentStatus": "Full-time",
    "vacancies": { "count": 5, "icon": "fa-users" },
    "position": { "title": "Software Engineer", "icon": "fa-laptop-code" },
    "weeklyHours": { "hours": 40, "icon": "fa-clock" },
    "salary": { "amount": "14.5 LPA", "icon": "fa-money-bill" },
    "workplace": "WFO",
    "qualification": "B.E./B.Tech in IT or related discipline",
    "experience": "3-5 years"
  },
  {
    "jobId": "jkl92shs82lqw",
    "companyLogo": "https://logo.clearbit.com/byjus.com",
    "companyName": "BYJU'S",
    "state": "Maharashtra",
    "jobDescription": "BYJU’S is hiring academic counselors who can interact with students and parents, understand their needs, and recommend appropriate BYJU’S learning products.",
    "employmentStatus": "Part-time",
    "vacancies": { "count": 8, "icon": "fa-users" },
    "position": { "title": "Academic Counselor", "icon": "fa-user-graduate" },
    "weeklyHours": { "hours": 20, "icon": "fa-clock" },
    "salary": { "amount": "4.8 LPA", "icon": "fa-money-bill" },
    "workplace": "Office",
    "qualification": "Any Graduate",
    "experience": "0-2 years"
  },
  {
    "jobId": "93hdk2jsf73a",
    "companyLogo": "https://logo.clearbit.com/tcs.com",
    "companyName": "TCS",
    "state": "Tamil Nadu",
    "jobDescription": "TCS is looking for a backend developer experienced in Java and Spring Boot. You will design REST APIs, integrate third-party services, and optimize database operations.",
    "employmentStatus": "Full-time",
    "vacancies": { "count": 6, "icon": "fa-users" },
    "position": { "title": "Backend Developer", "icon": "fa-database" },
    "weeklyHours": { "hours": 40, "icon": "fa-clock" },
    "salary": { "amount": "9 LPA", "icon": "fa-money-bill" },
    "workplace": "WFO",
    "qualification": "B.Tech/MCA",
    "experience": "2-3 years"
  },
  {
    "jobId": "qwl32jnd6tfa",
    "companyLogo": "https://logo.clearbit.com/wipro.com",
    "companyName": "Wipro",
    "state": "Haryana",
    "jobDescription": "Hiring remote customer support executives who can handle queries via phone, chat, and email. Excellent communication skills required.",
    "employmentStatus": "Freelancer",
    "vacancies": { "count": 10, "icon": "fa-users" },
    "position": { "title": "Customer Support Executive", "icon": "fa-headset" },
    "weeklyHours": { "hours": 30, "icon": "fa-clock" },
    "salary": { "amount": "3 LPA", "icon": "fa-money-bill" },
    "workplace": "Remote",
    "qualification": "12th Pass/Graduate",
    "experience": "0-1 year"
  },
  {
    "jobId": "29sf3lkf84kd",
    "companyLogo": "https://logo.clearbit.com/accenture.com",
    "companyName": "Accenture",
    "state": "Delhi",
    "jobDescription": "Looking for a data analyst proficient in SQL and Power BI. Responsibilities include data visualization, data cleaning, and generating reports for business decisions.",
    "employmentStatus": "Full-time",
    "vacancies": { "count": 2, "icon": "fa-users" },
    "position": { "title": "Data Analyst", "icon": "fa-chart-line" },
    "weeklyHours": { "hours": 40, "icon": "fa-clock" },
    "salary": { "amount": "10 LPA", "icon": "fa-money-bill" },
    "workplace": "WFO",
    "qualification": "B.Sc in Statistics/Mathematics or equivalent",
    "experience": "1-3 years"
  },
  {
    "jobId": "ksf8sdh29ajs",
    "companyLogo": "https://logo.clearbit.com/zoho.com",
    "companyName": "Zoho",
    "state": "Tamil Nadu",
    "jobDescription": "We are hiring content writers who can write technical articles, blogs, and product documentation with SEO best practices.",
    "employmentStatus": "Part-time",
    "vacancies": { "count": 4, "icon": "fa-users" },
    "position": { "title": "Content Writer", "icon": "fa-pen-nib" },
    "weeklyHours": { "hours": 25, "icon": "fa-clock" },
    "salary": { "amount": "3.6 LPA", "icon": "fa-money-bill" },
    "workplace": "Remote",
    "qualification": "BA/MA in English, Journalism",
    "experience": "1+ year"
  },
  {
    "jobId": "aa39skdf983q",
    "companyLogo": "https://logo.clearbit.com/flipkart.com",
    "companyName": "Flipkart",
    "state": "Uttar Pradesh",
    "jobDescription": "Flipkart is looking for warehouse managers to manage stock, oversee shipments, and maintain order records efficiently using ERP systems.",
    "employmentStatus": "Full-time",
    "vacancies": { "count": 7, "icon": "fa-users" },
    "position": { "title": "Warehouse Manager", "icon": "fa-box" },
    "weeklyHours": { "hours": 45, "icon": "fa-clock" },
    "salary": { "amount": "5.5 LPA", "icon": "fa-money-bill" },
    "workplace": "Office",
    "qualification": "B.Com or Diploma in Logistics",
    "experience": "2-4 years"
  },
  {
    "jobId": "djk39slajd9q",
    "companyLogo": "https://logo.clearbit.com/zomato.com",
    "companyName": "Zomato",
    "state": "Rajasthan",
    "jobDescription": "Delivery executives required for part-time food delivery. Flexible hours and attractive incentives available. Must have a bike and valid driving license.",
    "employmentStatus": "Freelancer",
    "vacancies": { "count": 15, "icon": "fa-users" },
    "position": { "title": "Delivery Executive", "icon": "fa-motorcycle" },
    "weeklyHours": { "hours": 20, "icon": "fa-clock" },
    "salary": { "amount": "2.4 LPA", "icon": "fa-money-bill" },
    "workplace": "Field",
    "qualification": "No formal education required",
    "experience": "0+ years"
  },
  {
    "jobId": "z81kslqp3u7f",
    "companyLogo": "https://logo.clearbit.com/infosys.com",
    "companyName": "Infosys",
    "state": "Punjab",
    "jobDescription": "We are looking for a system administrator with good knowledge of Linux/Windows systems. Should be able to manage servers, backups, and user accounts.",
    "employmentStatus": "Full-time",
    "vacancies": { "count": 3, "icon": "fa-users" },
    "position": { "title": "System Administrator", "icon": "fa-server" },
    "weeklyHours": { "hours": 40, "icon": "fa-clock" },
    "salary": { "amount": "6 LPA", "icon": "fa-money-bill" },
    "workplace": "Office",
    "qualification": "BCA/MCA/BSc-IT",
    "experience": "2-5 years"
  },{
    jobId: "90bc1b9ec7be44",
    companyLogo: "https://logo.clearbit.com/adobe.com",
    companyName: "Adobe",
    state: "Himachal Pradesh",
    jobDescription: "Design UI/UX for SaaS apps",
    employmentStatus: "Full-time",
    vacancies: { count: 5, icon: "fa-users" },
    position: { title: "UX Designer", icon: "fa-pencil-ruler" },
    weeklyHours: { hours: 30, icon: "fa-clock" },
    salary: { amount: "6-10 LPA", icon: "fa-money-bill" },
    workplace: "Remote",
    qualification: "Diploma",
    experience: "Fresher"
  },
  {
    jobId: "048ac0bb8c8f46",
    companyLogo: "https://logo.clearbit.com/intel.com",
    companyName: "Intel",
    state: "Gujarat",
    jobDescription: "Work on embedded systems and chip design",
    employmentStatus: "Full-time",
    vacancies: { count: 5, icon: "fa-users" },
    position: { title: "Embedded Developer", icon: "fa-microchip" },
    weeklyHours: { hours: 20, icon: "fa-clock" },
    salary: { amount: "15 LPA", icon: "fa-money-bill" },
    workplace: "Office",
    qualification: "B.Sc",
    experience: "Fresher"
  },
  {
    jobId: "f46a8a7fc5f042",
    companyLogo: "https://logo.clearbit.com/olacabs.com",
    companyName: "Ola",
    state: "Karnataka",
    jobDescription: "Drive and earn with flexible timings",
    employmentStatus: "Freelancer",
    vacancies: { count: 8, icon: "fa-users" },
    position: { title: "Driver Partner", icon: "fa-car" },
    weeklyHours: { hours: 40, icon: "fa-clock" },
    salary: { amount: "3.6 LPA", icon: "fa-money-bill" },
    workplace: "Field",
    qualification: "B.Tech",
    experience: "2-4 years"
  },
  {
    jobId: "c6fa1595baf344",
    companyLogo: "https://logo.clearbit.com/paytm.com",
    companyName: "Paytm",
    state: "Delhi",
    jobDescription: "Develop Android/iOS apps using Flutter",
    employmentStatus: "Full-time",
    vacancies: { count: 10, icon: "fa-users" },
    position: { title: "Mobile Developer", icon: "fa-mobile-alt" },
    weeklyHours: { hours: 40, icon: "fa-clock" },
    salary: { amount: "10 LPA", icon: "fa-money-bill" },
    workplace: "Field",
    qualification: "Any Graduate",
    experience: "1-3 years"
  },
  {
    jobId: "9719cf32d35c49",
    companyLogo: "https://logo.clearbit.com/freshworks.com",
    companyName: "Freshworks",
    state: "Tamil Nadu",
    jobDescription: "Provide L2 support for SaaS products",
    employmentStatus: "Part-time",
    vacancies: { count: 6, icon: "fa-users" },
    position: { title: "Technical Support Engineer", icon: "fa-headset" },
    weeklyHours: { hours: 30, icon: "fa-clock" },
    salary: { amount: "5.2 LPA", icon: "fa-money-bill" },
    workplace: "Office",
    qualification: "12th Pass",
    experience: "5+ years"
  },
  {
    jobId: "bd397cc6ab684f",
    companyLogo: "https://logo.clearbit.com/redbus.in",
    companyName: "Redbus",
    state: "Telangana",
    jobDescription: "Coordinate travel operations",
    employmentStatus: "Full-time",
    vacancies: { count: 6, icon: "fa-users" },
    position: { title: "Operations Executive", icon: "fa-bus" },
    weeklyHours: { hours: 40, icon: "fa-clock" },
    salary: { amount: "4.5 LPA", icon: "fa-money-bill" },
    workplace: "WFO",
    qualification: "MCA",
    experience: "1-3 years"
  },
  {
    jobId: "b2e8a573e75e41",
    companyLogo: "https://logo.clearbit.com/meesho.com",
    companyName: "Meesho",
    state: "Madhya Pradesh",
    jobDescription: "Run digital ad campaigns",
    employmentStatus: "Full-time",
    vacancies: { count: 4, icon: "fa-users" },
    position: { title: "Marketing Associate", icon: "fa-bullhorn" },
    weeklyHours: { hours: 40, icon: "fa-clock" },
    salary: { amount: "6 LPA", icon: "fa-money-bill" },
    workplace: "WFO",
    qualification: "B.E.",
    experience: "2-4 years"
  },
  {
    jobId: "85c4035b88c44d",
    companyLogo: "https://logo.clearbit.com/nykaa.com",
    companyName: "Nykaa",
    state: "Maharashtra",
    jobDescription: "Manage online product listings and offers",
    employmentStatus: "Full-time",
    vacancies: { count: 8, icon: "fa-users" },
    position: { title: "E-commerce Manager", icon: "fa-shopping-cart" },
    weeklyHours: { hours: 30, icon: "fa-clock" },
    salary: { amount: "7.5 LPA", icon: "fa-money-bill" },
    workplace: "Field",
    qualification: "B.Sc",
    experience: "5+ years"
  },
  {
    jobId: "a3393d31966d41",
    companyLogo: "https://logo.clearbit.com/delhivery.com",
    companyName: "Delhivery",
    state: "Haryana",
    jobDescription: "Track and manage courier shipments",
    employmentStatus: "Full-time",
    vacancies: { count: 10, icon: "fa-users" },
    position: { title: "Logistics Coordinator", icon: "fa-truck" },
    weeklyHours: { hours: 30, icon: "fa-clock" },
    salary: { amount: "4.8 LPA", icon: "fa-money-bill" },
    workplace: "Remote",
    qualification: "B.Sc",
    experience: "5+ years"
  },
  {
    jobId: "98831e9949704b",
    companyLogo: "https://logo.clearbit.com/cred.club",
    companyName: "Cred",
    state: "Karnataka",
    jobDescription: "Lead product strategy and roadmap",
    employmentStatus: "Full-time",
    vacancies: { count: 9, icon: "fa-users" },
    position: { title: "Product Manager", icon: "fa-lightbulb" },
    weeklyHours: { hours: 40, icon: "fa-clock" },
    salary: { amount: "18 LPA", icon: "fa-money-bill" },
    workplace: "Remote",
    qualification: "Any Graduate",
    experience: "5+ years"
  }
];

export default JobsData;